#define VER 101
#define NORMAL_ORERATION
#define MAX_PWM_EL 2450
#define MAX_PWM_PL 1500
#define MAX_PWM_AZ 2450

#define SERVO_MIDPOINT 1500
#define SERIAL_COM_SPEED 115200

#define MAG_DECLINIATION  0.0f
#define DEFAULT_PGAIN 70
#define MINIMAL_GAIN 5
//#define MINIMAL_CMD_THRESHOLD 300
//#define ANALOG_POT_LPF
#define LPF_FACTOR 0.995f
#define EL_POT_MIDPOINT_VALUE 550
#define PL_POT_MIDPOINT_VALUE 550
#define AZ_POT_MIDPOINT_VALUE 90

#define EL_ENDPOINT_LOW 200
#define EL_ENDPOINT_HIGH 900
#define PL_ENDPOINT_LOW 200
#define PL_ENDPOINT_HIGH 1000
#define AZ_ENDPOINT_LOW 70
#define AZ_ENDPOINT_HIGH 130

#define POT_SAMPLES 30
#define NOISE_OFFSET 12
#define POT_AVERAGE_SAMPLES 30

//#define CALIBRATE_MOTOR
